### ISSUE TITLE
Multiple Rocketlets: Include Folder in log

### ISSUE THREAD

**Issue by mrsimpson** [graywolf336/temporary-rocketlets-dev-environment#2]
When packaging a dev environment with multiple rocketlets, the log does not read which rocketlet is affected by the error message:
```
[08:30:20] Starting 'package-for-develop'...
[08:30:20] ✖ rocketlet.json has 7 validation error(s)
[08:30:20]    › Error: Missing required property: name
```

How to reproduce: Create a new folder in `rocketlets`, add a `rocketlet.json` with an empty object `{}` and run `npm start`

**Comment by graywolf336** [comment]
Yes indeed 👍

**Comment by graywolf336** [comment]
This is actually currently in place and is outputted after the validation errors:

```
[03:44:53] ✖ github/rocketlet.json
```

But I am going to change it to say:

```
[03:44:53] ✖ github/rocketlet.json has failed to validate
```

**Comment by graywolf336** [comment]
![image](https://user-images.githubusercontent.com/850391/27859872-cf6f876e-613f-11e7-96e2-858662680594.png)
